"""
test_live_apis.py — Standalone Diagnostic & Proof Suite for Cartesia & AssemblyAI APIs.
Run this script to prove that your live API keys are actively communicating with
the official Cartesia and AssemblyAI production endpoints.
"""

import os
import sys
import time
import json
import asyncio
import requests
import aiohttp
import websockets
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

ASSEMBLYAI_API_KEY = os.getenv("ASSEMBLYAI_API_KEY", "").strip()
CARTESIA_API_KEY = os.getenv("CARTESIA_API_KEY", "").strip()
CARTESIA_VOICE_ID = os.getenv("CARTESIA_VOICE_ID", "db6b0ed5-d5d3-463d-ae85-518a07d3c2b4").strip()

def mask_key(k: str) -> str:
    if len(k) <= 8:
        return "***"
    return f"{k[:6]}...{k[-4:]}"

print("\n" + "=" * 75)
print("  PHARMAREFILL AI — LIVE API DIAGNOSTIC & VERIFICATION SUITE")
print("=" * 75)
print(f"AssemblyAI API Key: {mask_key(ASSEMBLYAI_API_KEY)}")
print(f"Cartesia API Key:   {mask_key(CARTESIA_API_KEY)}")
print(f"Cartesia Voice ID:  {CARTESIA_VOICE_ID} (Skylar - Friendly Guide)")
print("=" * 75 + "\n")

# -------------------------------------------------------------
# TEST 1: Cartesia Sonic-2 Live TTS & Audio Generation
# -------------------------------------------------------------
def test_cartesia_live():
    print("[TEST 1/3] Testing Cartesia Sonic-2 Live TTS Endpoint...")
    if not CARTESIA_API_KEY or "your_" in CARTESIA_API_KEY:
        print("  ❌ ERROR: CARTESIA_API_KEY is not set or contains placeholder.\n")
        return False

    url = "https://api.cartesia.ai/tts/bytes"
    headers = {
        "X-API-Key": CARTESIA_API_KEY,
        "Cartesia-Version": "2024-06-10",
        "Content-Type": "application/json"
    }
    
    test_phrase = "Hello! This is a live voice generated by Cartesia Sonic-2 for Community Care Pharmacy."
    payload = {
        "model_id": "sonic-2",
        "transcript": test_phrase,
        "voice": {
            "mode": "id",
            "id": CARTESIA_VOICE_ID
        },
        "output_format": {
            "container": "wav",
            "encoding": "pcm_s16le",
            "sample_rate": 24000
        },
        "voice_settings": {
            "speed": 0.92
        }
    }

    t0 = time.time()
    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=10)
        latency = int((time.time() - t0) * 1000)
        
        if resp.status_code == 200:
            audio_bytes = resp.content
            output_file = Path("cartesia_test_output.wav")
            output_file.write_bytes(audio_bytes)
            
            print(f"  ✅ SUCCESS: Cartesia returned HTTP 200 in {latency}ms!")
            print(f"  📦 Audio Format: {resp.headers.get('Content-Type')}")
            print(f"  📊 Audio Size:   {len(audio_bytes):,} bytes")
            print(f"  💾 Saved Audio:  {output_file.resolve()} (Open to listen to real Skylar voice!)")
            print(f"  🔗 You can also check your API request count on: https://play.cartesia.ai/usage\n")
            return True
        else:
            print(f"  ❌ FAILED: Cartesia returned HTTP {resp.status_code}")
            print(f"  Details: {resp.text}\n")
            return False
    except Exception as e:
        print(f"  ❌ EXCEPTION: Could not reach Cartesia: {e}\n")
        return False

# -------------------------------------------------------------
# TEST 2: AssemblyAI LeMUR / LLM Gateway Clinical Audit
# -------------------------------------------------------------
def test_assemblyai_llm_gateway():
    print("[TEST 2/3] Testing AssemblyAI LeMUR / LLM Gateway Endpoint...")
    if not ASSEMBLYAI_API_KEY or "your_" in ASSEMBLYAI_API_KEY:
        print("  ❌ ERROR: ASSEMBLYAI_API_KEY is not set or contains placeholder.\n")
        return False

    url = "https://llm-gateway.assemblyai.com/v1/chat/completions"
    headers = {
        "authorization": ASSEMBLYAI_API_KEY,
        "content-type": "application/json"
    }

    transcript_sample = """
    Caller: Hello, I need to refill my Atorvastatin Calcium 20mg.
    Agent: Understood Eleanor. I can also synchronize your Metformin HCl 500mg and Lisinopril 10mg for Friday pickup.
    Caller: Yes please, sync them all.
    Agent: Done. Your co-pay is $19.90. Ready for Friday pickup.
    """

    payload = {
        "model": "qwen3.5-4b-32k-fast",
        "messages": [
            {"role": "system", "content": "You are a clinical pharmacy audit assistant. Return valid JSON only with keys: patient_name, medications, total_copay."},
            {"role": "user", "content": f"Extract structured clinical audit from this transcript:\n{transcript_sample}"}
        ],
        "max_tokens": 500,
        "temperature": 0.1
    }

    t0 = time.time()
    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=12)
        latency = int((time.time() - t0) * 1000)

        if resp.status_code == 200:
            result = resp.json()
            content = result["choices"][0]["message"]["content"]
            print(f"  ✅ SUCCESS: AssemblyAI LLM Gateway returned HTTP 200 in {latency}ms!")
            print(f"  🤖 Model Used: {result.get('model', 'qwen3.5-4b-32k-fast')}")
            print(f"  📝 Live Extraction Result:\n{content}")
            print(f"  🔗 You can also check your usage on: https://www.assemblyai.com/app\n")
            return True
        else:
            print(f"  ❌ FAILED: AssemblyAI LLM Gateway returned HTTP {resp.status_code}")
            print(f"  Details: {resp.text}\n")
            return False
    except Exception as e:
        print(f"  ❌ EXCEPTION: Could not reach AssemblyAI LLM Gateway: {e}\n")
        return False

# -------------------------------------------------------------
# TEST 3: AssemblyAI v3 Universal Streaming WebSocket Handshake
# -------------------------------------------------------------
async def test_assemblyai_streaming_ws():
    print("[TEST 3/3] Testing AssemblyAI v3 Universal Streaming WebSocket...")
    if not ASSEMBLYAI_API_KEY or "your_" in ASSEMBLYAI_API_KEY:
        print("  ❌ ERROR: ASSEMBLYAI_API_KEY is not set.\n")
        return False

    url = "wss://streaming.assemblyai.com/v3/ws?sample_rate=16000"
    headers = {"Authorization": ASSEMBLYAI_API_KEY}

    t0 = time.time()
    try:
        async with websockets.connect(url, additional_headers=headers) as ws:
            # 1. Wait for Begin message
            msg = await asyncio.wait_for(ws.recv(), timeout=5.0)
            latency = int((time.time() - t0) * 1000)
            data = json.loads(msg)
            print(f"  ✅ SUCCESS: Connected to AssemblyAI Universal Streaming v3 in {latency}ms!")
            print(f"  Handshake Message: {data}")
            
            # Send session termination
            await ws.send(json.dumps({"type": "Terminate"}))
            print("  Session terminated cleanly.\n")
            return True
    except Exception as e:
        print(f"  ❌ EXCEPTION: Could not connect to streaming WebSocket: {e}\n")
        return False

if __name__ == "__main__":
    c_ok = test_cartesia_live()
    a_ok = test_assemblyai_llm_gateway()
    w_ok = asyncio.run(test_assemblyai_streaming_ws())

    print("=" * 75)
    print("  VERIFICATION SUMMARY")
    print("=" * 75)
    print(f"  1. Cartesia Sonic-2 Audio Synthesis:     {'✅ ACTIVE & VERIFIED' if c_ok else '❌ FAILED'}")
    print(f"  2. AssemblyAI LeMUR / LLM Gateway Audit: {'✅ ACTIVE & VERIFIED' if a_ok else '❌ FAILED'}")
    print(f"  3. AssemblyAI Real-Time WebSocket STT:   {'✅ ACTIVE & VERIFIED' if w_ok else '❌ FAILED'}")
    print("=" * 75 + "\n")
