'use client';

import React, { useEffect, useState } from 'react';
import { Check, Copy, Download, FileText, RefreshCw, X } from 'lucide-react';
import { apiJson } from '@/lib/api';

interface SoapResponse {
  patient_id: string;
  patient_name: string;
  session_id?: string;
  date_recorded: string;
  soap: { subjective: string; objective: string; assessment: string; plan: string };
  icd10_codes: string[];
  generated_by: string;
  author: string;
}

interface SoapNoteModalProps {
  isOpen: boolean;
  onClose: () => void;
  patientId?: string;
  patientName?: string;
  sessionId?: string;
}

const SECTIONS: Array<[keyof SoapResponse['soap'], string]> = [
  ['subjective', 'S — Subjective'],
  ['objective', 'O — Objective'],
  ['assessment', 'A — Assessment'],
  ['plan', 'P — Plan'],
];

const asText = (d: SoapResponse) =>
  [
    `PHARMACIST SOAP NOTE — ${d.patient_name} (${d.patient_id}) — ${d.date_recorded}`,
    d.session_id ? `Session: ${d.session_id}` : '',
    ...SECTIONS.map(([k, label]) => `\n${label}\n${d.soap[k]}`),
    `\nICD-10: ${d.icd10_codes.join(', ')}`,
    `Generated by: ${d.generated_by}`,
    d.author,
  ]
    .filter(Boolean)
    .join('\n');

export const SoapNoteModal: React.FC<SoapNoteModalProps> = ({ isOpen, onClose, patientId, patientName, sessionId }) => {
  const [data, setData] = useState<SoapResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const generate = async () => {
    if (!patientId) return;
    setLoading(true);
    setError(null);
    try {
      setData(await apiJson<SoapResponse>('/api/clinical/soap-note', {
        method: 'POST',
        body: JSON.stringify({ patient_id: patientId, session_id: sessionId }),
      }));
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, patientId, sessionId]);

  if (!isOpen) return null;

  const copy = () => {
    if (!data) return;
    navigator.clipboard.writeText(asText(data));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  const download = () => {
    if (!data) return;
    const url = URL.createObjectURL(new Blob([asText(data)], { type: 'text/plain' }));
    const a = document.createElement('a');
    a.href = url;
    a.download = `SOAP_${data.patient_id}_${data.date_recorded}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4" role="dialog" aria-modal="true" aria-label="SOAP note">
      <div className="w-full max-w-3xl max-h-[90vh] flex flex-col bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl text-slate-100">
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-slate-800">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-cyan-400" />
            <div>
              <h2 className="text-sm font-bold">SOAP note — {data?.patient_name || patientName || 'Patient'}</h2>
              <p className="text-[11px] text-slate-400">{data ? data.generated_by : 'Generating…'}</p>
            </div>
          </div>
          <div className="flex items-center gap-1.5">
            <button onClick={generate} disabled={loading} title="Regenerate" className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 cursor-pointer"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button>
            <button onClick={copy} disabled={!data} title="Copy" className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 cursor-pointer">{copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}</button>
            <button onClick={download} disabled={!data} title="Download" className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 cursor-pointer"><Download className="h-4 w-4" /></button>
            <button onClick={onClose} title="Close" className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 cursor-pointer"><X className="h-4 w-4" /></button>
          </div>
        </div>
        <div className="p-5 overflow-y-auto space-y-4 text-sm">
          {!patientId && <p className="text-slate-400">Select a patient first.</p>}
          {error && <p className="text-rose-300 text-xs">{error}</p>}
          {data && (
            <>
              {SECTIONS.map(([k, label]) => (
                <section key={k}>
                  <h3 className="text-[11px] font-bold uppercase tracking-wide text-cyan-300 mb-1">{label}</h3>
                  <p className="whitespace-pre-wrap text-slate-200 leading-relaxed">{data.soap[k]}</p>
                </section>
              ))}
              <section>
                <h3 className="text-[11px] font-bold uppercase tracking-wide text-cyan-300 mb-1">ICD-10</h3>
                <p className="text-slate-300 text-xs">{data.icd10_codes.join(' · ') || 'None recorded'}</p>
              </section>
              <p className="text-[11px] text-amber-300 border-t border-slate-800 pt-3">{data.author}</p>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
