'use client';

import React, { useEffect, useState } from 'react';
import {
  Check,
  Copy,
  Download,
  FileText,
  RefreshCw,
  X,
  Quote,
  Award,
  Sparkles,
  ExternalLink,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import { apiJson } from '@/lib/api';
import { ComplianceCertificateModal } from './ComplianceCertificateModal';

interface SourceEvidenceItem {
  quote: string;
  speaker: string;
  confidence: number;
  claim: string;
}

interface SoapResponse {
  patient_id: string;
  patient_name: string;
  session_id?: string;
  date_recorded: string;
  soap: { subjective: string; objective: string; assessment: string; plan: string };
  icd10_codes: string[];
  source_evidence?: Record<string, SourceEvidenceItem[]>;
  generated_by: string;
  author: string;
}

interface SoapNoteModalProps {
  isOpen: boolean;
  onClose: () => void;
  patientId?: string;
  patientName?: string;
  sessionId?: string;
}

const SECTIONS: Array<[keyof SoapResponse['soap'], string, string]> = [
  ['subjective', 'S — Subjective', 'Patient history & chief complaint'],
  ['objective', 'O — Objective', 'Identity verification & prescription records'],
  ['assessment', 'A — Assessment', 'Clinical findings & 21 CFR § 1306 review'],
  ['plan', 'P — Plan', 'Dispensing queue & pickup commitments'],
];

const asText = (d: SoapResponse) =>
  [
    `PHARMACIST SOAP NOTE — ${d.patient_name} (${d.patient_id}) — ${d.date_recorded}`,
    d.session_id ? `Session ID: ${d.session_id}` : '',
    ...SECTIONS.map(([k, label]) => `\n${label}\n${d.soap[k]}`),
    `\nICD-10 Diagnoses: ${d.icd10_codes.join(', ')}`,
    `Generated by: ${d.generated_by}`,
    d.author,
  ]
    .filter(Boolean)
    .join('\n');

export const SoapNoteModal: React.FC<SoapNoteModalProps> = ({
  isOpen,
  onClose,
  patientId,
  patientName,
  sessionId,
}) => {
  const [data, setData] = useState<SoapResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [certModalOpen, setCertModalOpen] = useState(false);
  const [expandedEvidence, setExpandedEvidence] = useState<Record<string, boolean>>({
    subjective: true,
    objective: true,
    assessment: true,
    plan: true,
  });

  const toggleEvidence = (section: string) => {
    setExpandedEvidence((prev) => ({ ...prev, [section]: !prev[section] }));
  };

  const generate = async () => {
    if (!patientId) return;
    setLoading(true);
    setError(null);
    try {
      const res = await apiJson<SoapResponse>('/api/clinical/soap-note', {
        method: 'POST',
        body: JSON.stringify({ patient_id: patientId, session_id: sessionId }),
      });
      setData(res);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) generate();
  }, [isOpen, patientId, sessionId]);

  if (!isOpen) return null;

  const copy = () => {
    if (!data) return;
    navigator.clipboard.writeText(asText(data));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    if (!data) return;
    const url = URL.createObjectURL(new Blob([asText(data)], { type: 'text/plain' }));
    const a = document.createElement('a');
    a.href = url;
    a.download = `SOAP_${data.patient_id}_${data.date_recorded}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-150"
        role="dialog"
        aria-modal="true"
        aria-label="SOAP note"
      >
        <div className="w-full max-w-4xl max-h-[92vh] flex flex-col bg-slate-950 border border-cyan-500/30 rounded-3xl shadow-2xl shadow-cyan-500/10 text-slate-100 overflow-hidden">
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/60">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-2xl bg-cyan-500/20 border border-cyan-500/40 text-cyan-400">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h2 className="text-base font-bold text-white">
                    Clinical SOAP Note & Source Evidence Audit
                  </h2>
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
                    Transcript Grounded
                  </span>
                </div>
                <p className="text-xs text-slate-400">
                  Patient: <strong className="text-slate-200">{data?.patient_name || patientName || 'Patient'}</strong>{' '}
                  ({patientId}) · {data ? data.generated_by : 'Generating…'}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setCertModalOpen(true)}
                title="View Cryptographic Compliance Certificate"
                className="px-3 py-1.5 rounded-xl bg-emerald-500/20 hover:bg-emerald-500/30 border border-emerald-500/40 text-emerald-300 font-medium text-xs flex items-center gap-1.5 transition-colors cursor-pointer"
              >
                <Award className="h-3.5 w-3.5 text-emerald-400" />
                <span>Compliance Certificate</span>
              </button>
              <button
                onClick={generate}
                disabled={loading}
                title="Regenerate"
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 cursor-pointer transition-colors"
              >
                <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
              </button>
              <button
                onClick={copy}
                disabled={!data}
                title="Copy Text"
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 cursor-pointer transition-colors"
              >
                {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
              </button>
              <button
                onClick={download}
                disabled={!data}
                title="Download Note"
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 cursor-pointer transition-colors"
              >
                <Download className="h-4 w-4" />
              </button>
              <button
                onClick={onClose}
                title="Close"
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 cursor-pointer transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Body */}
          <div className="p-6 overflow-y-auto space-y-6 text-sm">
            {!patientId && <p className="text-slate-400">Select a patient first.</p>}
            {error && <p className="text-rose-300 text-xs">{error}</p>}
            {loading && (
              <div className="py-12 flex flex-col items-center justify-center gap-3 text-slate-400">
                <RefreshCw className="h-8 w-8 animate-spin text-cyan-400" />
                <p className="text-xs font-mono">Synthesizing clinical documentation and extracting evidence quotes…</p>
              </div>
            )}

            {data && !loading && (
              <>
                {/* 4 SOAP Sections */}
                {SECTIONS.map(([k, label, subtitle]) => {
                  const evidenceList = data.source_evidence?.[k] || [];
                  const isExpanded = expandedEvidence[k];

                  return (
                    <section
                      key={k}
                      className="p-4 rounded-2xl bg-slate-900/60 border border-slate-800/80 space-y-2.5 transition-all"
                    >
                      <div className="flex items-center justify-between">
                        <div>
                          <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400 flex items-center gap-2">
                            {label}
                          </h3>
                          <p className="text-[11px] text-slate-500">{subtitle}</p>
                        </div>
                        {evidenceList.length > 0 && (
                          <button
                            onClick={() => toggleEvidence(k)}
                            className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-[11px] text-cyan-300 flex items-center gap-1 cursor-pointer transition-colors"
                          >
                            <Quote className="h-3 w-3 text-cyan-400" />
                            <span>{evidenceList.length} Grounded Quote{evidenceList.length > 1 ? 's' : ''}</span>
                            {isExpanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                          </button>
                        )}
                      </div>

                      <p className="whitespace-pre-wrap text-slate-200 leading-relaxed font-sans text-sm">
                        {data.soap[k]}
                      </p>

                      {/* Grounded Source-Linked Evidence Quotes */}
                      {evidenceList.length > 0 && isExpanded && (
                        <div className="mt-3 pt-3 border-t border-slate-800/60 space-y-2">
                          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400 flex items-center gap-1.5">
                            <Sparkles className="h-3 w-3 text-amber-400" />
                            AssemblyAI Source-Linked Transcript Grounding:
                          </span>
                          <div className="space-y-1.5">
                            {evidenceList.map((ev, idx) => (
                              <div
                                key={idx}
                                className="p-2.5 rounded-xl bg-slate-950/80 border border-cyan-500/20 flex items-start justify-between gap-3 text-xs"
                              >
                                <div className="space-y-0.5">
                                  <div className="flex items-center gap-2">
                                    <span
                                      className={`px-1.5 py-0.5 rounded text-[9px] font-bold ${
                                        ev.speaker === 'Caller'
                                          ? 'bg-blue-500/20 text-blue-300'
                                          : 'bg-emerald-500/20 text-emerald-300'
                                      }`}
                                    >
                                      {ev.speaker === 'Caller' ? '🎙️ Caller' : '🛡️ Agent'}
                                    </span>
                                    <span className="text-[10px] text-slate-400 font-medium">
                                      Claim: {ev.claim}
                                    </span>
                                  </div>
                                  <p className="text-slate-200 font-mono text-[11px] italic">
                                    &ldquo;{ev.quote}&rdquo;
                                  </p>
                                </div>
                                <div className="shrink-0 flex items-center gap-1 px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-[10px] text-emerald-300 font-mono">
                                  <span>{Math.round(ev.confidence * 1000) / 10}% Conf</span>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </section>
                  );
                })}

                {/* ICD-10 Coding */}
                <section className="p-4 rounded-2xl bg-slate-900/60 border border-slate-800/80 space-y-1.5">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
                    Validated ICD-10 Conditions
                  </h3>
                  <div className="flex flex-wrap gap-2 pt-1">
                    {data.icd10_codes.map((code, idx) => (
                      <span
                        key={idx}
                        className="px-2.5 py-1 rounded-xl bg-slate-800 border border-slate-700 text-xs text-slate-300 font-mono"
                      >
                        {code}
                      </span>
                    ))}
                  </div>
                </section>

                {/* Pharmacist Signature Block */}
                <div className="p-4 rounded-2xl bg-gradient-to-r from-slate-900 via-slate-900/90 to-amber-950/30 border border-amber-500/30 flex items-center justify-between text-xs">
                  <div>
                    <p className="text-amber-300 font-medium">{data.author}</p>
                    <p className="text-slate-400 text-[11px]">
                      Cryptographically indexed under Title 21 CFR § 1306 compliance chain.
                    </p>
                  </div>
                  <button
                    onClick={() => setCertModalOpen(true)}
                    className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs flex items-center gap-1.5 cursor-pointer transition-colors"
                  >
                    <span>View Digital Seal</span>
                    <ExternalLink className="h-3 w-3 text-cyan-400" />
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Compliance Certificate Modal */}
      <ComplianceCertificateModal
        isOpen={certModalOpen}
        onClose={() => setCertModalOpen(false)}
        sessionId={sessionId || 'DEMO-SESSION-001'}
      />
    </>
  );
};
