"""
States and Escalation Reason Enums for PharmaRefill AI (RxTriage).
"""
from enum import Enum

class AgentState(str, Enum):
    GREETING_AND_CONSENT = "GREETING_AND_CONSENT"
    AUTHENTICATION = "AUTHENTICATION"
    INTENT_TRIAGE = "INTENT_TRIAGE"
    MED_SYNC_PROPOSAL = "MED_SYNC_PROPOSAL"
    COPAY_CONFIRMATION = "COPAY_CONFIRMATION"
    PICKUP_COMMITMENT = "PICKUP_COMMITMENT"
    PRESCRIBER_INTAKE = "PRESCRIBER_INTAKE"
    CALL_COMPLETED = "CALL_COMPLETED"
    ESCALATE_HUMAN = "ESCALATE_HUMAN"

class EscalationReason(str, Enum):
    DEA_CONTROLLED_SUBSTANCE = "DEA_CONTROLLED_SUBSTANCE"
    EMERGENCY_ADVERSE_REACTION = "EMERGENCY_ADVERSE_REACTION"
    RETRY_LIMIT_EXCEEDED = "RETRY_LIMIT_EXCEEDED"
    UNRESOLVABLE_INTENT = "UNRESOLVABLE_INTENT"
    CALLER_REQUEST = "CALLER_REQUEST"
    ZERO_REFILLS_DOCTOR_RENEWAL = "ZERO_REFILLS_DOCTOR_RENEWAL"
    PRIOR_AUTH_REQUIRED = "PRIOR_AUTH_REQUIRED"
